[workspace]
members = ["byte-utils", "can-port", "io-utils", "serial-port", "yamcs-bridge", "yamcs-derive"]
resolver = "3"

[workspace.dependencies]
bytes = "1.10"
mio = {version = "1", features = ["os-poll", "os-ext"] }
nexosim = { git = "https://github.com/asynchronics/nexosim.git", rev = "0d0864" }
nexosim-util = { git = "https://github.com/asynchronics/nexosim.git", rev = "0d0864" }
schematic = "0.18"
serde = "1"
thread-guard = "0.1.0"
tracing = { version = "0.1.40", default-features = false, features = [
    "std",
]}
