// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Timestamp {
    #[prost(sint64, required, tag = "1")]
    pub millis: i64,
    #[prost(uint32, required, tag = "2")]
    pub picos: u32,
}
/// An aggregate value is an ordered list of (member name, member value).
/// Two arrays are used in order to be able to send just the values (since
/// the names will not change)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AggregateValue {
    #[prost(string, repeated, tag = "1")]
    pub name: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "2")]
    pub value: ::prost::alloc::vec::Vec<Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumeratedValue {
    #[prost(sint64, required, tag = "1")]
    pub sint64_value: i64,
    #[prost(string, required, tag = "4")]
    pub string_value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArrayValue {
    #[prost(message, repeated, tag = "1")]
    pub value: ::prost::alloc::vec::Vec<Value>,
}
/// Union type for storing a value
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Value {
    #[prost(oneof = "value::V", tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 12, 14")]
    pub v: ::core::option::Option<value::V>,
}
/// Nested message and enum types in `Value`.
pub mod value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum V {
        #[prost(float, tag = "2")]
        FloatValue(f32),
        #[prost(double, tag = "3")]
        DoubleValue(f64),
        #[prost(sint32, tag = "4")]
        Sint32Value(i32),
        #[prost(uint32, tag = "5")]
        Uint32Value(u32),
        #[prost(bytes, tag = "6")]
        BinaryValue(::prost::alloc::vec::Vec<u8>),
        #[prost(string, tag = "7")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag = "8")]
        TimestampValue(super::Timestamp),
        #[prost(uint64, tag = "9")]
        Uint64Value(u64),
        #[prost(sint64, tag = "10")]
        Sint64Value(i64),
        #[prost(bool, tag = "11")]
        BooleanValue(bool),
        #[prost(message, tag = "13")]
        EnumeratedValue(super::EnumeratedValue),
        #[prost(message, tag = "12")]
        AggregateValue(super::AggregateValue),
        #[prost(message, tag = "14")]
        ArrayValue(super::ArrayValue),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterValue {
    /// Parameter identifier.
    /// It has to match the id defined in the ParameterDefinition
    #[prost(uint32, required, tag = "1")]
    pub id: u32,
    /// Raw value (uncalibrated)
    #[prost(message, optional, tag = "3")]
    pub raw_value: ::core::option::Option<Value>,
    /// Engineering value (calibrated)
    #[prost(message, optional, tag = "4")]
    pub eng_value: ::core::option::Option<Value>,
    #[prost(message, optional, tag = "5")]
    pub acquisition_time: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub generation_time: ::core::option::Option<Timestamp>,
    /// How long (in milliseconds) this parameter value is valid
    #[prost(int64, optional, tag = "10")]
    pub expire_millis: ::core::option::Option<i64>,
}
/// this message is sent from the Gateway to Yamcs
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterData {
    #[prost(message, repeated, tag = "1")]
    pub parameters: ::prost::alloc::vec::Vec<ParameterValue>,
    /// The next three fields are used by the recorder as unique key to store
    /// parameters in "rows" and also by components that provide parameters
    /// from external sources.
    #[prost(string, required, tag = "2")]
    pub group: ::prost::alloc::string::String,
    #[prost(uint32, required, tag = "3")]
    pub seq_num: u32,
    /// if all parameters have the same generation time, it can be skipped from the
    /// value and provided here
    #[prost(message, optional, tag = "4")]
    pub generation_time: ::core::option::Option<Timestamp>,
    /// if all parameters have the same aquisition time, it can be skipped from the
    /// value and provided here
    #[prost(message, optional, tag = "5")]
    pub acquisition_time: ::core::option::Option<Timestamp>,
}
/// this message is sent from Yamcs to the Gateway
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterUpdates {
    #[prost(message, repeated, tag = "1")]
    pub parameters: ::prost::alloc::vec::Vec<ParameterValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandAssignment {
    #[prost(string, required, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub raw_value: ::core::option::Option<Value>,
    #[prost(message, optional, tag = "3")]
    pub eng_value: ::core::option::Option<Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandId {
    #[prost(int64, required, tag = "1")]
    pub generation_time: i64,
    #[prost(string, required, tag = "2")]
    pub origin: ::prost::alloc::string::String,
    /// unique in relation to generationTime and origin
    #[prost(int32, required, tag = "3")]
    pub sequence_number: i32,
    #[prost(string, optional, tag = "4")]
    pub command_name: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreparedCommand {
    #[prost(message, required, tag = "1")]
    pub command_id: CommandId,
    #[prost(message, repeated, tag = "2")]
    pub assignments: ::prost::alloc::vec::Vec<CommandAssignment>,
    #[prost(map = "string, message", tag = "3")]
    pub extra: ::std::collections::HashMap<::prost::alloc::string::String, Value>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub binary: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandAck {
    #[prost(message, required, tag = "1")]
    pub command_id: CommandId,
    #[prost(enumeration = "command_ack::AckStatus", required, tag = "2")]
    pub ack: i32,
    #[prost(string, required, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, required, tag = "4")]
    pub time: Timestamp,
    #[prost(string, optional, tag = "5")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub return_pv: ::core::option::Option<ParameterValue>,
}
/// Nested message and enum types in `CommandAck`.
pub mod command_ack {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AckStatus {
        Na = 0,
        Scheduled = 1,
        Pending = 2,
        Ok = 3,
        Nok = 4,
        Timeout = 5,
        Cancelled = 6,
        Disabled = 7,
    }
    impl AckStatus {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                AckStatus::Na => "NA",
                AckStatus::Scheduled => "SCHEDULED",
                AckStatus::Pending => "PENDING",
                AckStatus::Ok => "OK",
                AckStatus::Nok => "NOK",
                AckStatus::Timeout => "TIMEOUT",
                AckStatus::Cancelled => "CANCELLED",
                AckStatus::Disabled => "DISABLED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NA" => Some(Self::Na),
                "SCHEDULED" => Some(Self::Scheduled),
                "PENDING" => Some(Self::Pending),
                "OK" => Some(Self::Ok),
                "NOK" => Some(Self::Nok),
                "TIMEOUT" => Some(Self::Timeout),
                "CANCELLED" => Some(Self::Cancelled),
                "DISABLED" => Some(Self::Disabled),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(string, optional, tag = "1")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "2")]
    pub generation_time: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub reception_time: ::core::option::Option<i64>,
    #[prost(int32, optional, tag = "4")]
    pub seq_number: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "5")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, required, tag = "6")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration = "EventSeverity", optional, tag = "7", default = "Info")]
    pub severity: ::core::option::Option<i32>,
    /// Set by API when event was posted by a user
    #[prost(string, optional, tag = "10")]
    pub created_by: ::core::option::Option<::prost::alloc::string::String>,
    /// Additional properties
    #[prost(map = "string, string", tag = "11")]
    pub extra: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// YGE nodes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeList {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<Node>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Link {
    #[prost(uint32, required, tag = "1")]
    pub id: u32,
    #[prost(string, required, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub tm: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub tc: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Node {
    #[prost(uint32, required, tag = "1")]
    pub id: u32,
    #[prost(string, required, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub tm: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub tc: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "6")]
    pub links: ::prost::alloc::vec::Vec<Link>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterDefinition {
    /// parameter name relative to the namespace defined in the Yamcs configuration
    #[prost(string, required, tag = "1")]
    pub relative_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub unit: ::core::option::Option<::prost::alloc::string::String>,
    /// ptype is the type of the parameter
    /// it can be a fully qualified name of a type known inside Yamcs
    /// or a basic value type sint32, uint32, etc in case it is a simple
    /// engineering only value
    #[prost(string, required, tag = "4")]
    pub ptype: ::prost::alloc::string::String,
    #[prost(bool, optional, tag = "5")]
    pub writable: ::core::option::Option<bool>,
    /// numeric parameter id used when sending the values
    /// the id has to be unique for one node
    #[prost(uint32, required, tag = "6")]
    pub id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterDefinitionList {
    #[prost(message, repeated, tag = "1")]
    pub definitions: ::prost::alloc::vec::Vec<ParameterDefinition>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandArgument {
    #[prost(string, required, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub unit: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, required, tag = "4")]
    pub argtype: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub default_value: ::core::option::Option<Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandDefinition {
    /// command name relative to the namespace defined in the Yamcs configuration
    #[prost(string, required, tag = "1")]
    pub relative_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub arguments: ::prost::alloc::vec::Vec<CommandArgument>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandDefinitionList {
    #[prost(message, repeated, tag = "1")]
    pub definitions: ::prost::alloc::vec::Vec<CommandDefinition>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkStatus {
    #[prost(enumeration = "LinkState", required, tag = "1")]
    pub state: i32,
    #[prost(uint64, required, tag = "2")]
    pub data_in_count: u64,
    #[prost(uint64, required, tag = "3")]
    pub data_out_count: u64,
    #[prost(uint64, required, tag = "4")]
    pub data_in_size: u64,
    #[prost(uint64, required, tag = "5")]
    pub data_out_size: u64,
    /// / if there was an error this may provide more details
    #[prost(string, optional, tag = "6")]
    pub err: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkCommand {
    #[prost(uint32, required, tag = "1")]
    pub link_id: u32,
    #[prost(string, required, tag = "2")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub args: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    NodeInfo = 1,
    ParameterDefinitions = 2,
    CommandDefinitions = 3,
    Tm = 4,
    Tc = 5,
    Event = 6,
    /// sent from Gateway to Yamcs
    ParameterData = 7,
    LinkCommand = 8,
    LinkStatus = 9,
    /// send from Yamcs to the Gateway
    ParameterUpdates = 10,
    TcAck = 11,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            MessageType::NodeInfo => "NODE_INFO",
            MessageType::ParameterDefinitions => "PARAMETER_DEFINITIONS",
            MessageType::CommandDefinitions => "COMMAND_DEFINITIONS",
            MessageType::Tm => "TM",
            MessageType::Tc => "TC",
            MessageType::Event => "EVENT",
            MessageType::ParameterData => "PARAMETER_DATA",
            MessageType::LinkCommand => "LINK_COMMAND",
            MessageType::LinkStatus => "LINK_STATUS",
            MessageType::ParameterUpdates => "PARAMETER_UPDATES",
            MessageType::TcAck => "TC_ACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_INFO" => Some(Self::NodeInfo),
            "PARAMETER_DEFINITIONS" => Some(Self::ParameterDefinitions),
            "COMMAND_DEFINITIONS" => Some(Self::CommandDefinitions),
            "TM" => Some(Self::Tm),
            "TC" => Some(Self::Tc),
            "EVENT" => Some(Self::Event),
            "PARAMETER_DATA" => Some(Self::ParameterData),
            "LINK_COMMAND" => Some(Self::LinkCommand),
            "LINK_STATUS" => Some(Self::LinkStatus),
            "PARAMETER_UPDATES" => Some(Self::ParameterUpdates),
            "TC_ACK" => Some(Self::TcAck),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventSeverity {
    Info = 0,
    Warning = 1,
    Error = 2,
    Watch = 3,
    Distress = 5,
    Critical = 6,
    Severe = 7,
}
impl EventSeverity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EventSeverity::Info => "INFO",
            EventSeverity::Warning => "WARNING",
            EventSeverity::Error => "ERROR",
            EventSeverity::Watch => "WATCH",
            EventSeverity::Distress => "DISTRESS",
            EventSeverity::Critical => "CRITICAL",
            EventSeverity::Severe => "SEVERE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INFO" => Some(Self::Info),
            "WARNING" => Some(Self::Warning),
            "ERROR" => Some(Self::Error),
            "WATCH" => Some(Self::Watch),
            "DISTRESS" => Some(Self::Distress),
            "CRITICAL" => Some(Self::Critical),
            "SEVERE" => Some(Self::Severe),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LinkState {
    Ok = 1,
    Unavail = 2,
    Disabled = 3,
    Failed = 4,
}
impl LinkState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LinkState::Ok => "OK",
            LinkState::Unavail => "UNAVAIL",
            LinkState::Disabled => "DISABLED",
            LinkState::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OK" => Some(Self::Ok),
            "UNAVAIL" => Some(Self::Unavail),
            "DISABLED" => Some(Self::Disabled),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
