[package]
name = "nexosim-yamcs-bridge"
# When incrementing version and releasing to crates.io:
# - Update crate version in this Cargo.toml
# - Update crate version in README.md
# - Update dependency in sibling crates
# - Remove path dependencies
# - Update CHANGELOG.md
# - Update if necessary copyright notice in LICENSE-MIT
# - Create a "vX.Y.Z" git tag
authors = ["Asynchronics"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/asynchronics/nexosim-protocols"
readme = "README.md"
homepage = "https://github.com/asynchronics/nexosim-protocols/yamcs-bridge"
version = "0.2.0"
edition = "2024"
rust-version = "1.88.0"
publish = ["nexosim"]

[features]
derive = ["dep:nexosim-yamcs-derive"]

[dependencies]
bytes = { workspace = true }
nexosim = { workspace = true }
nexosim-yamcs-derive = { version = "0.2.0", optional = true }
prost = "0.13"
schematic = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { version = "1", features = ["io-util", "net", "rt", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = { version = "0.1", default-features = false }
tracing = { workspace = true }

[dev-dependencies]
schematic = { workspace = true, features = ["toml"] }

[target.'cfg(yamcs_bridge_codegen)'.build-dependencies]
prost-build = { version = "0.13" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(yamcs_bridge_codegen)'] }
