[package]
name = "nexosim-yamcs-derive"
# When incrementing version and releasing to crates.io:
# - Update crate version in this Cargo.toml
# - Update crate version in README.md
# - Update dependency in sibling crates
# - Remove path dependencies
# - Update CHANGELOG.md
# - Update if necessary copyright notice in LICENSE-MIT
# - Create a "vX.Y.Z" git tag
authors = ["Asynchronics"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/asynchronics/nexosim-protocols"
readme = "README.md"
homepage = "https://github.com/asynchronics/nexosim-protocols/yamcs-derive"
version = "0.2.0"
edition = "2024"
description="""
Yamcs bridge types macros for NeXosim-based simulations.
"""
categories = ["simulation", "aerospace", "science"]
keywords = [
    "simulation",
    "discrete-event",
    "systems",
    "cyberphysical",
    "real-time",
    "serial-port",
]

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = "2.0"
